name: "PR review approval action"
author: "Patrick Wei"
description: "PR review approval action"
branding:
  icon: "check"
  color: "blue"
inputs:
  github-token:
    description: "The GitHub token"
    required: true
  pr-approval:
    description: "PR check approve this PR or not"
    required: true
  pr-message:
    description: "The PR comments"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.pr-approval }}
    - ${{ inputs.pr-message }}